Feature: add "xunit" reporter
tmorell/license-compliance pull request #79
Opened 2021-03-28 16:56 UTC by flo-sch

- feat(formatters): add new xunit formatter
  - add new Xunit formatter (using xmlbuilder internally) with summary and detailed test suites
  - add unit tests for xunit formatter covering all reporters
  - allow "xunit" formatter in configuration validation
- docs(README): add xunit to --format list

Resolves #70

2021-03-28 16:58 UTC, flo-sch commented
NB: xunit is mainly about the stucture of the generated XML.
The XML nodes structure is arbitrary here, I chose the format that worked in my Bitbucket Pipelines example

2021-03-29 23:54 UTC, tmorell requested changes

2021-03-29 23:54 UTC, tmorell commented on README.md
> +* `-f, --format <format>` Report format, csv, text, json or xunit (default = "text").
Add Oxford comma:
"..json, or xunit..."

2021-03-29 23:54 UTC, tmorell commented on package.json
> +        "xmlbuilder": "^15.1.1"
Remove ^: "xmlbuilder": "15.1.1".
License number must be specific for Renovate.

2021-03-29 23:54 UTC, tmorell commented on src/formatters/factory.ts
> +        const classes = { Csv, Json, Text, Xunit };
Missing UT in /home/teo/projects/temp/license-compliance/tests/formatters/factory.spec.ts

2021-03-30 22:00 UTC, tmorell approved these changes

2021-03-30 22:01 UTC, merged